"""create_agents_and_agent_wallets_tables

Revision ID: 5dab280981c2
Revises: f163836ddab6
Create Date: 2025-11-22 13:24:13.744757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dab280981c2'
down_revision = 'f163836ddab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_agent_wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('wallet_address', sa.Text(), nullable=False),
    sa.Column('delegated_smart_wallet', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', name='tbl_agent_wallets_ux_agent_id'),
    sa.UniqueConstraint('wallet_address', name='tbl_agent_wallets_ux_wallet_address')
    )
    op.create_table('tbl_agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('emoji', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_agents')
    op.drop_table('tbl_agent_wallets')
    # ### end Alembic commands ###
